test::
	./p2.sh

clean::
	find . -type f -name '*.o' -delete
	find . -type f -name '*.myret' -delete
	find . -type f -name '*.diff' -delete
	find . -type f -name '*.myout' -delete
	find . -type f -name '*.asm' -delete
	find . -type f -name 'a.out' -delete
